Repository Learn-Build-Teach/deals-for-devs, pull requests merged in 2024-03, with the labels that each got.

#57 feat: add issue templates
  .github/ISSUE_TEMPLATE/bug-report-🐛.md
  .github/ISSUE_TEMPLATE/documentation-📝.md
  .github/ISSUE_TEMPLATE/feature-request-⚙️.md
Labels: 📚 Documentation, ✨ Feature, Low Priority

#61 feat: add template for pull requests
  .github/pull_request_template.md
Labels: 📚 Documentation, ✨ Feature, Low Priority

#70 feat: add aria-label to input
  src/app/deals/add/DealForm.tsx
  src/components/Footer.tsx
  src/components/nav/Nav.tsx
Labels: 🐛 Bug, Medium Priority, a11y

#69 feat: added logic to use safeparse instead of parse
  src/actions/deals.ts
  src/actions/subscriber-subscribe.ts
Labels: ✨ Feature, High Priority

#86 docs: updated and re-structured pull_request_template
  .github/pull_request_template.md
Labels: 📚 Documentation, 🚀 Enhancement, Low Priority

#85 Use layouts and pages for admin routes
  src/app/(admin)/dashboard/deals/page.tsx
  src/app/(admin)/dashboard/layout.tsx
  src/app/(admin)/dashboard/page.tsx
  src/app/(admin)/dashboard/subscribers/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/dashboard/AdminNav.tsx
  src/components/dashboard/Dashboard.tsx
  src/components/deals/Deal.tsx
  src/components/deals/DealsList.tsx
  src/components/subscriber/SubscriberList.tsx
Labels: 🚀 Enhancement

#99 docs: included a link to the figma file
  .github/contributing.md
Labels: 📚 Documentation, 🚀 Enhancement
